#!/usr/bin/env bash

reload_wm() {
    sed -i"" \
        -e "s/bg.color: #.*/bg.color: ${color7:-#FFFFFF}/" \
        -e "s/text.color: #.*/text.color: ${color0:-#000000}/" \
        -e "s/image.color: #.*/image.color: ${color0:-#000000}/" \
        "${HOME}/.themes/thicc/openbox-3/themerc"
    openbox --reconfigure
}

