#! /bin/sh

source ~/.scripts/theme_config

# config options
bspc config border_width            4
bspc config top_padding             $(echo $geometry | sed 's/.*x//;s/+.*+/+/' | bc)
bspc config window_gap              15
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config history_aware_focus     true
bspc config auto_cancel             true

# desktops
bspc monitor -d main web term misc foo

# Rules
bspc rule -a firefox desktop=^2
bspc rule -a Gimp-2.8 desktop=^4 floating=on
bspc rule -a Gimp desktop=^4 floating=on
bspc rule -a lxappearance floating=on center=true
bspc rule -a gmrun floating=on center=true

# colors
bspc config focused_border_color ${focused_border_color}
bspc config normal_border_color ${normal_border_color}
bspc config active_border_color ${active_border_color}
bspc config focused_locked_border_color ${focused_locked_border_color}
bspc config normal_locked_border_color ${normal_locked_border_color}
bspc config active_locked_border_color ${active_locked_border_color}
bspc config urgent_border_color ${urgent_border_color}
bspc config presel_border_color ${presel_border_color}

# Autostart apps
compton --shadow-exclude '!focused' &
mpd &
xsetroot -cursor_name left_ptr &
restart_panel.sh &

