#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
hsetroot -solid "#212121"

bspc monitor -d I II III I

bspc config border_width 5
bspc config window_gap 40

bspc config focused_border_color "#5f865f"

bspc config split_ratio 0.4
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Alacritty state=floating
bspc rule -a Firefox state=floating
bspc rule -a mpv state=floating
