#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III I

bspc config border_width 5
bspc config window_gap 40

bspc config split_ratio 0.4
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Alacritty state=floating
