#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 3
bspc config window_gap 24

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config focus_follows_pointer true

bspc config normal_border_color "#3c3836"
bspc config focused_border_color "#665c54"
bspc config presel_feedback_color "#7c6f64"

bspc rule -a Gimp desktop='^4' state=floating follow=on
wal -i "$(< "${HOME}/.cache/wal/wal")" -o "wal-set"
