#!/bin/sh

# Source colors
source ~/.scripts/colors/output/colors.sh

while :; do
    echo "       $(neofetch --stdout memory) %{c}$(date "+%a %d %b %l:%M %p")%{r}$(mpc current | cut -c 1-25)      %{r}"
	sleep 2s
done |

lemonbar -b -g "500x33+710+33" -f "-benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1" -f"-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" -B "#$white" -F "#$gray"

