#!/bin/sh

# Source colors
source ~/.scripts/colors/output/colors.sh

icon() {
    echo -n -e "\u$1"
}

ram () {
    free="$(egrep 'MemFree' /proc/meminfo | egrep -o '[0-9]*')"
    total="$(egrep 'MemTotal' /proc/meminfo | egrep -o '[0-9]*')"
    used=$((total-free))
    percent=$(echo "100*$used/$total" | bc)
    echo "         $(icon e0c5) $percent %"
}

mpc_title () {
    echo $(mpc current -f "%artist%[ - %title%]" | cut -c 1-25)
}

while :; do
    echo "$(ram) %{c}$(date "+%a %d %b %l:%M %p")%{r}$(icon e0ec) $(mpc_title)  %{r}"
	sleep 2s
done |

lemonbar -p -b -g "500x33+710+33" -f '-benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1' -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1' -B "#$white" -F "#$gray"

