#!/bin/sh
# Script to easily map commands to keys in openbox

volup () {
    # amixer set Master 5+
    pulseaudio-ctl up
    notify-send -t 1 -r 112 "$(pulseaudio-ctl | grep -o -E '[0-9][0-9] \%')"
}

voldown () {
    # amixer set Master 5-
    pulseaudio-ctl down
    notify-send -t 1 -r 112 "$(pulseaudio-ctl | grep -o -E '[0-9][0-9] \%')"
}

prevsong () {
    mpc prev
    current="$(mpc current)"
    notify-send -t 1 -r 112 "$current"
}

nextsong () {
    mpc next
    current="$(mpc current)"
    notify-send -t 1 -r 112 "$current"
}

togglesong () {
    mpc toggle

    current="$(mpc current)"
    width=$(txtw "$current")
    if [ "$(mpc | awk -F '\\[|\\]' '/\[/ {printf $2}' 2>/dev/null)" == "playing" ]; then
        notify-send -t 1 -r 112 "$current"
    else
        notify-send -t 1 -r 112 "Pause"
    fi
}

dmenu () {
    source ~/.cache/wal/colors.sh
    dmenu_run -s 0 -i -h 30 -w 120 -q -x 30 -y 30 -sb "$color15" -sf "$color0" -nb "$color15" -nf "$color0" -fn "-benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1" -p ">" -l 1
}


case $1 in
    volup) volup ;;
    voldown) voldown ;;
    prevsong) prevsong ;;
    nextsong) nextsong ;;
    togglesong) togglesong ;;
    dmenu) dmenu ;;
esac

