#!/bin/bash

main() {
    cd ~/Music
    notify-send -t 5 "Starting MP3 Download !"
    url="$1"
    youtube-dl --extract-audio --audio-format mp3 $url
    notify-send -t 5 "Downloaded mp3: $url"
}

main "$@"
