#!/usr/bin/env bash
#
# rofi with flags for my PC/Laptop.

source "${HOME}/.cache/wal/colors.sh"

[[ "$HOSTNAME" == "bonez" ]] && \
    font="Roboto 25"

rofi -show run \
     -font "${font:-Artwiz Lemon 7}" \
     -separator-style none \
     -scrollbar-width 0 \
     # -location 1 \
     # -yoffset 30 \
     -lines 10 \
     -width 20 \
     -bw 10 \
     -padding 10 \
     -color-window "$color0" "$color1" "$color0"\
