#! /bin/bash
fip-groove () {
    mpc clear
    mpc add http://aifae8cah8.lb.vip.cdn.dvmr.fr/fip-webradio3.mp3 
    mpc play
    popup -e "fip groove"
}

fip-jazz () {
    mpc clear
    mpc add http://aifae8cah8.lb.vip.cdn.dvmr.fr/fip-webradio2.mp3 
    mpc play
    popup -e "fip jazz"
}

fip-rock () {
    mpc clear
    mpc add http://aifae8cah8.lb.vip.cdn.dvmr.fr/fip-webradio1.mp3 
    mpc play
    popup -e "fip rock"
}

fip-monde () {
    mpc clear
    mpc add http://aifae8cah8.lb.vip.cdn.dvmr.fr/fip-webradio4.mp3 
    mpc play
    popup -e "fip monde"
}

fip-nouveau () {
    mpc clear
    mpc add http://aifae8cah8.lb.vip.cdn.dvmr.fr/fip-webradio5.mp3 
    mpc play
    popup -e "fip nouveau"
}

bfm () {
    mpc clear
    mpc add http://aifae8cah8.lb.vip.cdn.dvmr.fr/bfmbusiness
    mpc play
    popup -e "BFM"
}

case $1 in
    groove) fip-groove ;; 
    rock) fip-rock ;; 
    jazz) fip-jazz ;; 
    monde) fip-monde ;; 
    nouveau) fip-nouveau ;; 
    bfm) bfm ;; 
esac
