#!/bin/sh

#█▓▒░ vars
#FULL=▓
FULL=━
#FULL=┅
#EMPTY=░
#EMPTY=━
#EMPTY=─
EMPTY=┄
BLOCK=██

name=$USER
host=`hostname`
battery=/sys/class/power_supply/BAT1
distro="arch linux"
kernel=`uname -r`

#█▓▒░ ANSI
initializeANSI() {
  esc=""
  blackf="${esc}[30m";   blackb="${esc}[1;30m";
  redf="${esc}[31m";     redb="${esc}[1;31m";
  greenf="${esc}[32m";   greenb="${esc}[1;32m";
  yellowf="${esc}[33m";  yellowb="${esc}[1;33m";
  bluef="${esc}[34m";    blueb="${esc}[1;34m";
  purplef="${esc}[35m";  purpleb="${esc}[1;35m";
  cyanf="${esc}[36m";    cyanb="${esc}[1;36m";
  whitef="${esc}[37m";   whiteb="${esc}[1;37m";
  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"
  reset="${esc}[0m"
}

#█▓▒░ greets
greet() {
printf "${reset} hello ${greenf}$name${reset} i'm ${redf}$host${reset}\n"
printf "${reset}\n"
}

#█▓▒░ progress bar
draw() {
  perc=$1
  size=$2
  inc=$(( perc * size / 100 ))
  out=""
  for v in `seq 0 $(( size - 1 ))`; do
    test "$v" -le "$inc"   \
    && out="${out}${redf}${FULL}${reset}" \
    || out="${out}${blackb}${EMPTY}${reset}"
  done
  printf $out
}

#█▓▒░ colors
colors() {
cat << EOF
 ${redf}${BLOCK}${reset}${redb}${BLOCK}${reset} ${greenf}${BLOCK}${reset}${greenb}${BLOCK}${reset} ${yellowf}${BLOCK}${reset}${yellowb}${BLOCK}${reset} ${bluef}${BLOCK}${reset}${blueb}${BLOCK}${reset} ${purplef}${BLOCK}${reset}${purpleb}${BLOCK}${reset} ${cyanf}${BLOCK}${reset}${cyanb}${BLOCK}${reset}
EOF
# ${whitef}${BLOCK}${reset}${whiteb}${BLOCK}${reset} ${whitef}${BLOCK}${reset}${whiteb}${BLOCK}${reset} ${whitef}${BLOCK}${reset}${whiteb}${BLOCK}${reset} ${whitef}${BLOCK}${reset}${whiteb}${BLOCK}${reset} ${whitef}${BLOCK}${reset}${whiteb}${BLOCK}${reset} ${whitef}${BLOCK}${reset}${whiteb}${BLOCK}${reset}
 }

#█▓▒░ environment
list() {
printf "${reset}${bluef} ${1} ${reset}${2}\n"
}

#█▓▒░ new line
new_line(){
printf "\n"
}

#█▓▒░ cpu
show_cpu() {
cpu=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
c_lvl=`printf "%.0f" $cpu`
printf "${redf}%-4s ${bluef}%-5s %-25s \n" " cpu" "$c_lvl%" `draw $c_lvl 15` 
}

#█▓▒░ ram
show_ram() {
ram=`free | awk '/Mem:/ {print int($3/$2 * 100.0)}'`
printf "${redf}%-4s ${bluef}%-5s %-25s \n" " ram" "$ram%" `draw $ram 15` 
}

#█▓▒░ main
main() {
    initializeANSI
    new_line
    colors
    new_line
    greet
    list distro $distro
    list kernel $kernel
    new_line
    show_cpu
    show_ram
}

main
