#!/usr/bin/env bash
# vim: set ft=sh:
#
# Depends on: xorg-xrandr, mpc, lemonbar, ip, wmctrl

font="${BAR_FONT:-"-*-lemon-*"}"
icon="${BAR_ICON:-"-*-siji-*"}"
height="${BAR_HEIGHT:-36}"


get_workspaces2(){
    # Create a dynamic workspace switcher.
    workspaces="$(wmctrl -d | awk -v fg="${color8:-#F0F0F0}" \
                                  '$6!="0,0"{next}
                                   $2=="-"{printf "  %{F"fg"}" $NF "  %{F}"}
                                   $2=="*"{printf "  " $NF "  "}')"
    printf "%s\\n" "$workspaces"
}


get_workspaces() {
    bar=$(bspc wm -g | tr ":" "\n")
    workspaces=""
    empty_icon=""
    occup_icon=""
    urgen_icon=""
    for part in $bar; do
        case ${part:0:1} in
            "M")
                workspaces="$workspaces  $empty_icon "
                ;;
            "O")
                workspaces="$workspaces  $occup_icon  "
                ;;
            "F")
                workspaces="$workspaces  $empty_icon  "
                ;;
            "o")
                workspaces="$workspaces  %{F${color8:-#F0F0F0}}$occup_icon%{F}  "
                ;;
            "f")
                workspaces="$workspaces  %{F${color8:-#F0F0F0}}$empty_icon%{F}  "
                ;;
            "U")
                workspaces="$workspaces  %{F${color2:-#F0F0F0}}$urgen_icon%{F}  "
                ;;
            *) ;;
        esac
    done
    printf "%s\\n" "$workspaces"
}



get_date() {
    # Get the date and time.
    printf "%s\\n" "$(date +"%a %d %b - %l:%M %p")"
}


get_song() {
    # Get the current song from mopidy/mpd.
    printf "%.100s\\n" "$(mpc current -f '%title%')"
}


get_volume() {
    # Get the system volume.
    volume="$(amixer sget Master | grep -o -m 1 -E "[[:digit:]]+%")"

    case "$volume" in
        0%|[0-9]%)   vol_icon=" " ;;
        1?%|2?%|3?%) vol_icon="" ;;
        4?%|5?%|6?%) vol_icon="" ;;
        *) vol_icon="" ;;
    esac

    printf "%s\\n" "$(icon "$vol_icon") ${volume}"

}


icon() {
    # Format an icon.
    printf "%s\\n" "%{F${color8:-#F0F0F0}}${1}%{F}"
}


main() {
    # Main script function.

    # Import colors from 'wal'.
    # https://github.com/dylanaraps/pywal
    . "${HOME}/.cache/wal/colors.sh"

    # Info that doesn't need to grabbed more than once.
    bspc config top_padding "${height}"

    # Loop and print the info.
    while :; do
        workspaces="$(get_workspaces2)"
        date="$(get_date)"
        song="$(icon "") $(get_song)"
        volume="$(get_volume)"

        printf "%s%s%s\\n" \
               "%{l}   ${workspaces}" \
               "%{c}${date}" \
               "%{r}${song}  |  ${volume}    "
        sleep .1s
    done |\

    # Launch lemonbar.
    lemonbar -d -g "x${height}" \
             -B "${color0:-#000000}" -F "${color15:-#F0F0F0}"\
             -n "bar" -f "$font" -f "$icon"
}


main "$@"
