#!/usr/bin/env bash

font="${BAR_FONT:-"-*-lemon-*"}"
icon="${BAR_ICON:-"-*-siji-*"}"
height="${BAR_HEIGHT:-40}"

vol() {
    cur="$(amixer get Master -n | awk -F '\\[|\\]' '/[0-9]{1,3}%/ {print $2" "$6}')"

    case "$cur" in
        [0-9]%*|*f*) vol_icon="\\ue0e3" ;;
        [1-4]?%*)    vol_icon="\\ue0e1" ;;
        [5-6]?%*|*)  vol_icon="\\ue0e0" ;;
    esac

    printf "%b" "  $vol_icon ${cur/ *}%"
}

tim() {
    printf "%(%a %d %b  - %l:%M %p)T"
}

bri() {
    cur="$(< /sys/class/backlight/intel_backlight/brightness)"
    printf "%b" "$((cur / 30))% \\uf0eb"
}

bat() {
    cur="$(< /sys/class/power_supply/BAT0/capacity)"
    sta="$(< /sys/class/power_supply/BAT0/status)"

    case "$cur" in
        [0-9])  bat_icon="\\ue243" ;;
        [1-3]?) bat_icon="\\ue245" ;;
        [4-5]?) bat_icon="\\ue247" ;;
        [6-7]?) bat_icon="\\ue249" ;;
        *)      bat_icon="\\ue24b" ;;
    esac

    [[ "$sta" != Discharging ]] && bat_icon+="  \\ue20e"


    printf "%s%%  %b" "$cur" "$bat_icon"
}

main(){
    # Import colors from xrdb
    color0="#$(xrdb -query | grep "^\*color0:" | cut -d '#' -f2)"
    color15="#$(xrdb -query | grep "^\*color15:" | cut -d '#' -f2)"

    for((;;)) {
        printf "   %s   \\n" " %{l}$(vol) %{c}$(tim)%{r} $(bat)"
        sleep 2
    } |\

    lemonbar -db \
            -g "500x${height}+433+30" \
            -f "$font" -f "$icon" \
            -n "bar" \
            -B "$color15" \
            -F "$color0"
}

main "$@"
