#!/usr/bin/env bash
#
# Change mpd song and display a notification.
#
# Created by Dylan Araps.
#
# Depends on: mpc, libnotify (patched with id support)
case "$1" in
    "next") mpc next ;;
    "prev") mpc prev ;;
    "toggle") mpc toggle ;;
    *) printf "%s\n" "Usage: ./song next, ./song prev"; exit ;;
esac

notify-send -t 1 "Song: $(mpc current)"
