#!/usr/bin/env bash

reload_wm() {
    bspc config normal_border_color "$color8"
    bspc config focused_border_color "$color1"
    bspc config presel_feedback_color "$color15"
    wid=$(xdo id -m -a "bar")
    xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
}


